#### Data spliting generator

In [21]:
import json, os

def train_test_file_split(train_range, test_range, dev_range, save_path, is_list=False):
    # internal utils
    def generate_file_list(start, end):
        return [f"bacteria_{i}.csv" for i in range(start, end+1)]
    
    # generate
    if not is_list:
        train_files = generate_file_list(*train_range)
        test_files  = generate_file_list(*test_range)
        dev_files   = generate_file_list(*dev_range)
    else:
        train_files = train_range
        test_files  = test_range
        dev_files   = dev_range

    data = {
        "train": train_files,
        "test":  test_files,
        "dev":   dev_files,
    }

    os.makedirs(os.path.dirname(save_path), exist_ok=True)

    with open(save_path, "w") as json_file:
        json.dump(data, json_file, indent=4)
    
    return True

In [22]:
train_test_file_split([2,4], [5, 6], [7, 8], "../data/cds/BacteriaCDS-ORFSeq2Class-v1/data_index.json")

True

In [23]:
# END

In [24]:
import json, os, random

In [25]:
with open('../data/cds/BacteriaCDS-ORFSeq2Class-v2/data_summary.json', 'r') as file:
    index = json.load(file)

In [27]:
len(index.keys())

4819

In [28]:
files = [f for f in os.listdir('../data/cds/BacteriaCDS-ORFSeq2Class-v2/database') if f.endswith('csv')]
len(files)

5742

In [30]:
train_ratio = 0.7
dev_ratio   = 0.2
test_ratio  = 0.1

random.shuffle(files)
train_size = int(len(files) * train_ratio)
dev_size   = int(len(files) * dev_ratio)

train_files = files[:train_size]
dev_files   = files[train_size:train_size + dev_size]
test_files  = files[train_size + dev_size:]

train_test_file_split(train_files, test_files, dev_files, "../data/cds/BacteriaCDS-ORFSeq2Class-v2/data_index.json", is_list=True)

True

In [34]:
with open('../data/cds/BacteriaCDS-ORFSeq2Class-v2/data_index.json', 'r') as file:
    index = json.load(file)

print(len(index["train"]))
print(len(index["dev"]))
print(len(index["test"]))

4019
1148
575

In [8]:
import pandas as pd
import json

with open('../data/cds/BacteriaCDS-ORFSeq2Class-v2/data_index.json', 'r') as file:
    index = json.load(file)

# --------------------------------------------------------------------------------
test_files = index["test"]
x = 10
merged_dfs = []
dfs = [pd.read_csv(f'../data/cds/BacteriaCDS-ORFSeq2Class-v2/balanced/{file}') for file in test_files[0:x]]
df1 = pd.concat(dfs, ignore_index=True)
print(df1.shape)
#df1.head()

dfs = [pd.read_csv(f'../data/cds/BacteriaCDS-ORFSeq2Class-v2/database/{file}') for file in test_files[0:x]]
df2 = pd.concat(dfs, ignore_index=True)
print(df2.shape)
#df1.head()

(22202, 2)
(96094, 2)

In [14]:
not_in_df = df1[~df1['sequence'].isin(df2['sequence'])]
not_in_df['len'] = not_in_df['sequence'].apply(len)
not_in_df

Empty DataFrame
Columns: [sequence, label, len]
Index: []

In [15]:
not_in_df= df2[~df2['sequence'].isin(df1['sequence'])]
not_in_df['len'] = not_in_df['sequence'].apply(len)
not_in_df

/tmp/ipykernel_3591100/905443142.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  not_in_df['len'] = not_in_df['sequence'].apply(len)

                                                sequence  label  len
0      CTGTTATTAAAACCTACTTTCTTACAAATATCACTAATACTCATGC...      0  147
1      TTGATTGCTTACAACAAACTTAGCTTGAGTCCCATTAAATGTAACT...      0  108
2      TTGCTACTAGACCTAATTTTTTATCTTGTAAAAATACTTGTCCAAA...      0  111
4      ATGTGGTCCATCTTAGCACAAGATTTTATAACTGCTGTAGGTCCAT...      0  147
5      TTGTTAAGTGCTGCTACAGGCTTTCCTACTACAAATAACATCAATA...      0  150
...                                                  ...    ...  ...
96088  TTGGAAACATCACGAGGGACTGCAAAACTTCGACGCAAAGCCCGCC...      0  108
96089  ATGCGGCCAATGCGCAGGATGCGATTGTGGTCCAGCAGGGGAACAC...      0  156
96090  GTGTACGCGAGACGAAATAATCACACATTTCCTGTTCTAATTCCTC...      0  159
96091  TTTTCAACATCAGCGCCCGAGGGGGCGCGCCAGCGGGGTTTGAGCT...      0  510
96093  TTGTCGCTGGCACCCTCGCCTTCTGGCTGTTCGGCAGTGCACTGGT...      0  141

[83869 rows x 3 columns]